
var mongoose = require('mongoose');
module.exports = mongoose.model('User',{
	id: String,
	username: String,
	password: String,
	email: String,
	names: String,
	surnames: String,
	sex: String,
	born: Date,
	street: String,
	distrit: String,
	city: String,
	code: Number,
	number: Number,
	facebook: String,
	twitter: String,
	instagram: String,
	account: String,
	bank: String,
	creditcard: String,
	bankcard: String,
	cardcv: String,
	name911: String,
	number911: String,
	comment: String,
	chat: String,
	academy: String,
	rutid: String,
	userkind: String,
	photoper: String
});
